### ISSUE TITLE
现在这个项目还跟进翻译吗?

### ISSUE THREAD

**Issue by wenzhihong2003** [cctanfujun/kotlin-web-site-cn#29]
现在这个项目还跟进翻译吗?

**Comment by Jween** [comment]
跟进, 不过最近比较忙, 15号后继续跟进

2015-12-06 6:33 GMT+08:00 tom.wen notifications@github.com:

**Comment by tianchengbaihe** [comment]
## 而且似乎也已找不到md文件了？

看到了，在ref分支上
