### ISSUE TITLE
Chrome下的小问题

### ISSUE THREAD

**Issue by hellokaton** [cctanfujun/kotlin-web-site-cn#32]
![_20151230150812](https://cloud.githubusercontent.com/assets/3849072/12047478/3b637896-af07-11e5-94d5-3115a73c2925.png)

**Comment by loshine** [comment]
审查元素发现由这段代码引起 @cctanfujun @biezhi @Jween 

46-64 行的注释提前结束未起作用

![image](https://cloud.githubusercontent.com/assets/11252444/13213173/e71c60f4-d981-11e5-85f2-fbc4a1fde112.png)

**Comment by cctanfujun** [comment]
已修复
