### ISSUE TITLE
访问 http://kotlinlang.cn/ 显示未备案无法访问

### ISSUE THREAD

**Issue by loshine** [cctanfujun/kotlin-web-site-cn#38]
如题所述

![image](https://cloud.githubusercontent.com/assets/11252444/13210562/90407ef2-d96b-11e5-937b-92c5c86a74b6.png)

**Comment by Jween** [comment]
稍等2周, 我正在将服务器从日本迁回国内, 并将整个网站更新到 Kotlin 1.0 正式版, 这两周内不可用

**Comment by Jween** [comment]
这段时间, kotlinlang官网会针对1.0版本进行改版

**Comment by loshine** [comment]
@Jween 这段时间我就用 github 这边的访问好了，谢谢了 ^ ^

**Comment by cctanfujun** [comment]
已修复

**Comment by fkwl** [comment]
好滴好滴

**Comment by cctanfujun** [comment]
已修复
