### ISSUE TITLE
认领翻译exceptions.md

### ISSUE THREAD

**Issue by whilu** [cctanfujun/kotlin-web-site-cn#7]
认领翻译interfaces.md（@cx9527 已经翻译好了exceptions.md，我就翻译了这篇）

**Comment by cctanfujun** [comment]
可是interfaces已经被认领了啊！。。。。。。

**Comment by whilu** [comment]
不好意思啊 ，，，我又眼瞎了一次。。。好吧  。。。

2015-10-13 21:56 GMT+08:00 谈釜君 notifications@github.com:

**Comment by cctanfujun** [comment]
翻译完成
